# Global
platform=ios
appium.url=http://127.0.0.1:4723
implicit.wait=10
explicit.wait=10
appium.newCommandTimeout=120
max.retry=2
# Android
android.deviceName=Pixel_10_Pro
android.platformVersion=17
android.automationName=UiAutomator2
android.app=apps/TheApp.apk
android.appPackage=com.appiumpro.the_app
android.appActivity=com.appiumpro.the_app.MainActivity
android.noReset=false
android.serverLaunchTimeout=60000
android.serverInstallTimeout=60000
# iOS
ios.deviceName=iPhone 16 Pro Max
ios.platformVersion=26.4
ios.automationName=XCUITest
ios.app=apps/TheApp.app
ios.bundleId=com.appiumpro.the_app
ios.noReset=false
# LambdaTest Cloud
execution.env=local
lt.username=
lt.accesskey=
lt.server.url=https://mobile-hub.lambdatest.com/wd/hub
# Android Cloud Config
lt.android.deviceName=.*
lt.android.platformVersion=13
lt.android.app=
# iOS Cloud Config
lt.ios.deviceName=iPhone.*
lt.ios.platformVersion=16
lt.ios.app=
lt.ios.bundleId=com.appiumpro.the_app