# Global
platform=ios
appium.url=http://127.0.0.1:4723
implicit.wait=10
explicit.wait=10
appium.newCommandTimeout=120
max.retry=2
# Android
android.deviceName=Pixel_10_Pro
android.platformVersion=17
android.automationName=UiAutomator2
android.app=apps/TheApp.apk
android.appPackage=com.appiumpro.the_app
android.appActivity=com.appiumpro.the_app.MainActivity
android.noReset=false
# iOS
ios.deviceName=iPhone 16 Pro Max
ios.platformVersion=26.4
ios.automationName=XCUITest
ios.app=apps/TheApp.app
ios.bundleId=com.appiumpro.the_app
ios.noReset=false
#userData
userName=alice
password=mypassword